//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Resources.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cakes
    {
        public Cakes()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int IdCake { get; set; }
        public string NameCake { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
    }
}
