//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Resources.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int IdClient { get; set; }
        public string NameClient { get; set; }
        public string LastnameClient { get; set; }
        public string PatronymicClient { get; set; }
        public int Phone { get; set; }
        public int IdZakaz { get; set; }
    
        public virtual Zakaz Zakaz { get; set; }
        public virtual User User { get; set; }
    }
}
