//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Resources.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public int IdIng { get; set; }
        public string NameIng { get; set; }
        public int Quantity { get; set; }
    }
}
